### PR TITLE
Remove ways to contribute, condense what we will try to do

### PR DESCRIPTION
**Pull request by libcce**
- Remove ways to contribute, it is handled via CONTRIBUTING.md and discuss.md in extras/
- Remove What we will try to do, Be excellent to each other, and Be patient with me and yourself sections. These sections are not consistent with the other LC lessons. Replace with a temporary brief description to align with other LC lessons.

### CODE REVIEW

**Comment by tpatwood** [comment]
I like both parts of this suggestion and would approve the merge...: 
- a big yes to removing the contributing information 
- I like bringing the git page in line with the other lesson pages 

... however, could the more colloquial content be brought into the first page of the lesson instead? Other lessons start out with this information (e.g., the intro to data has an outcome of 'don't be afraid to ask for help!')

**Comment by libcce** [comment]
@katrinleinweber @tpatwood would you recommend moving the "What will we do?" section to the introduction ahead of "What is version control?". I'm fine with keeping the content, I'm just trying to align the format of this lesson to the other lessons. So if there is another more appropriate place for it, let me know. Thanks 😄

**Comment by katrinleinweber** [comment]
I'm only opposed to deleting the "What will we do?" section and will go along with it being moved. I do think that its a very good part of the overview page there. Maybe the other lessons should be aligned with this one ;-)

**Comment by tpatwood** [comment]
I agree! Move the What will we do to the intro!

**Comment by katrinleinweber** [comment]
The merge conflict resulted from #62. I resolved it to @libcce suggestion, but remain with my https://github.com/LibraryCarpentry/lc-git/pull/53/#issuecomment-494469581 opinion ;-)

**Comment by libcce** [comment]
Per @katrinleinweber keeping 'what we will try to do' and removing 'ways to contribute' via https://github.com/LibraryCarpentry/lc-git/pull/65. Closing this PR.

**Pull request closed without merging**
